Repository edgexfoundry/go-mod-secrets, pull requests merged in 2021-04, with the labels that each got.

#103 fix(security): Fix JSON structure of token self response
  internal/pkg/vault/mock.go
  internal/pkg/vault/secrets.go
  internal/pkg/vault/secrets_test.go
  pkg/types/messages.go
  secrets/factory_test.go
Labels: 3-high, ireland, security-services

#105 refacotr!: TechDebt for refactor GenerateConsulToken API
  internal/pkg/vault/management.go
  internal/pkg/vault/management_test.go
  internal/pkg/vault/secrets.go
  internal/pkg/vault/secrets_test.go
  pkg/listener/poll_test.go
  secrets/interfaces.go
  secrets/mocks/SecretClient.go
  secrets/mocks/SecretStoreClient.go
Labels: ireland, tech-debt

#107 docs: Add badges to readme
  README.md
Labels: documentation
